Added Generic map handler
lxgr-linux/pokete pull request #111
Opened 2022-03-22 20:14 UTC by lxgr-linux

This is a feature that may be used later to generate playmaps directly from strings.

2022-04-05 15:07 UTC, MaFeLP commented on pokete_classes/npcs.py
>                                      info={"type": "duel", "player": self})
Due to the change in line 218, these lines need to be unindented by two spaces:

```suggestion
                                   if poke.hp > 0][0],
                                  self.poke,
                                  info={"type": "duel", "player": self})
```

2022-04-05 15:10 UTC, MaFeLP commented on pokete_classes/ob_maps.py
> +ob_maps = None
```suggestion
ob_maps = None

if __name__ == "__main__":
    print("\033[31;1mDo not execute this!\033[0m")
```

2022-04-05 15:27 UTC, MaFeLP commented on pokete.py
> +        self.last_center_map = obmp.ob_maps[_si.get("last_center_map", "playmap_1")]
line too long

```suggestion
        self.last_center_map = obmp.ob_maps[_si.get("last_center_map",
                                                    "playmap_1")]
```

2022-04-05 15:30 UTC, MaFeLP commented on pokete.py
>                                                       in_fight=True)
Due to adding `deck.` in line 428, this line need to be indented by further five spaces.

```suggestion
                                                          in_fight=True)
```

2022-04-05 15:38 UTC, MaFeLP commented on pokete.py
> +                                 (mvp.movemap.width - 2) * mvp.movemap.height - 1)[1:]
Line too long:

```suggestion
                                 (mvp.movemap.width - 2)
                                 * mvp.movemap.height - 1)[1:]
```

2022-04-05 15:39 UTC, MaFeLP commented on pokete.py
>                                     [1, -1, 0, 0], [0, 0, 1, -1]):
Lines too long

```suggestion
        for statement, x, y in zip([figure.x + 6 > mvp.movemap.x
                                    + mvp.movemap.width,
                                    figure.x < mvp.movemap.x + 6,
                                    figure.y + 6 > mvp.movemap.y
                                    + mvp.movemap.height,
                                    figure.y < mvp.movemap.y + 6],
```

2022-04-05 15:46 UTC, MaFeLP commented on pokete.py
>  world and be a Pokete-trainer.",
Due to adding `mvp.` to line 950, the indentation in these lines changes, which makes them too long:

```suggestion
                            " < You're now ten years old.",
                            " < And I think it's now time for you to travel \
the world and be a Pokete-trainer.",
```

PS: Please also fix indentation of lines 954-968, as GitHub doesn't let me make a suggestion in these lines

2022-04-05 15:50 UTC, MaFeLP commented on pokete.py
>                        map_data[ob_map]["dors"][dor])
Also rename this variable from `dor` to `door`

```suggestion
        for door in map_data[ob_map]["dors"]:
            parse_obj(_map, door,
                      Door(" ", state="float",
                           arg_proto=map_data[ob_map]["dors"][door]["args"]),
                      map_data[ob_map]["dors"][door])
```

2022-04-05 15:52 UTC, MaFeLP commented on pokete.py
>                                                "x": 17, "y": 16})
Due to renaming `ChangeDor` to `ChangeDoor`, these lines require one further space of indentation:

```suggestion
                                    arg_proto={"chance": 6,
                                               "map": "playmap_5",
                                               "x": 17, "y": 16})
```

2022-04-05 15:54 UTC, MaFeLP commented on pokete.py
> -    _map.dor = DorToCenter()
Due to changing `Dor` to `Door`, these lines require one further space of indentation:

```suggestion:
                               arg_proto={"map": "playmap_19",
                                          "x": 26, "y": 1})
```

2022-04-05 15:58 UTC, MaFeLP commented
I also found, that `pokete_classes.generic_map_handler` is commented in `pokete.py`. Do I have to specifically enable the map handler for it to be tested/used?

2022-04-05 22:09 UTC, lxgr-linux commented
Yes, that's true, since it does not have a real usecase as of now it's disabled.

2022-04-21 21:01 UTC, MaFeLP requested changes
While play testing for a while, I did not encounter any bugs/problems/crashes.

Maybe add these two doc strings and resolve the conversations afterwards:

- [number one](https://github.com/lxgr-linux/pokete/pull/111/files#r842893561)
- [bumber two](https://github.com/lxgr-linux/pokete/pull/111/files#r842893981)

Also there are some other minor things missing, but it looks very good otherwise!

2022-04-21 21:27 UTC, merged