Represent char
lxgr-linux/pokete pull request #113
Opened 2022-03-22 20:52 UTC by lxgr-linux

Added `represent_char` option to savefile so the player is able to change the their representation on the map from an `a` to something else.

2022-03-24 15:28 UTC, MaFeLP commented
Three things:

1. You should check for the length of the `represent_char` string, as having two characters or more, breaks the whole map behavior (you can not see the first line anymore and all the map downwards on shifts)
2. Exclude Unicode characters from settable characters, as they require sometimes a bit more space in a monospace font, than normal characters (test by setting `represent_char` to `😎` for example
3. Maybe add a dialogue box to the menu, that lets a player change their char easily, as this is a very nice feature!

2022-03-26 00:26 UTC, lxgr-linux commented
> Three things:
> 
> 1. You should check for the length of the `represent_char` string, as having two characters or more, breaks the whole map behavior (you can not see the first line anymore and all the map downwards on shifts)
> 2. Exclude Unicode characters from settable characters, as they require sometimes a bit more space in a monospace font, than normal characters (test by setting `represent_char` to `😎` for example
> 3. Maybe add a dialogue box to the menu, that lets a player change their char easily, as this is a very nice feature!

Done, back open for review.

2022-04-22 11:15 UTC, MaFeLP requested changes
Please add a Notification or some other indicator that the represent_char is invalid, as the user may not know, why their save file is not working and they are not using the `--log` option.

2022-04-24 19:32 UTC, lxgr-linux commented
> Please add a Notification or some other indicator that the represent_char is invalid, as the user may not know, why their save file is not working and they are not using the `--log` option.

Done

2022-04-28 21:18 UTC, MaFeLP requested changes
Apart from these two typos, this pull request looks good for merging!

2022-04-28 21:18 UTC, MaFeLP commented on pokete.py
> +                                            "The choosen chracater has to be a \
Fix typo

```suggestion
                                            "The chosen character has to be a \
```

2022-04-28 21:20 UTC, merged