Added time
lxgr-linux/pokete pull request #123
Opened 2022-04-14 00:05 UTC by lxgr-linux

Added:
- [x] Ingame time
- [x] A clock to keep track of it
- [x] Time stops after 120s of no input to avoid afk-ing
- [ ] Time depending NPCs
- [ ] Time depending Poketes

2022-05-01 20:16 UTC, MaFeLP commented
There is a bug that has to do with Pokete Care:

1. Putting a Pokete into care
2. Waiting for it to gain xp
3. Go the care and talk to the npc, answer `n` to the `do you want it back` question.
4. Go right by one and left by one (activating the npc dialog again)
5. Answer `y` to the `do you want it back` question.
6. Go to the pokete center and find out, you pokete has been duplicated.
7. Find out that the Deck will not close when either hitting `q` or `1` and that the python thread is hitting 100% your CPU performance.

2022-05-01 22:43 UTC, lxgr-linux commented
Thanks for the info.
The cause for this behavior was that when `Figure.add_poke` was called and a clear spot in the deck was present, the method added the poke in the clear spot and at the end.
It's fixed now.

2022-06-04 15:33 UTC, MaFeLP requested changes
Nice work!

2022-06-04 15:33 UTC, MaFeLP commented on gen_wiki.py
> +    def get_name(poke):
You missed using this method in line `218` when getting the name of the evolve pokete!

2022-06-04 15:33 UTC, MaFeLP commented on pokete_classes/timer.py
> +
```suggestion


```

2022-06-04 15:33 UTC, MaFeLP commented on pokete_classes/timer.py
> +    """Timer class to keep track of ingame time
```suggestion
    """Timer class to keep track of in-game time
```

2022-06-04 15:33 UTC, MaFeLP commented on pokete_classes/timer.py
> +        self.time = init_time  # time in ingame minutes
```suggestion
        self.time = init_time  # time in in-game minutes
```

2022-06-04 15:33 UTC, MaFeLP commented on pokete_classes/timer.py
> +    def formated(self):
```suggestion
    def formatted(self):
```

2022-06-04 15:33 UTC, MaFeLP commented on pokete_classes/timer.py
> +        """Returns the ingame time in a formated manner"""
```suggestion
        """Returns the in-game time in a formatted manner"""
```

2022-06-04 15:33 UTC, MaFeLP commented on pokete_classes/timer.py
> +        """Sets the las tinput time to the current time"""
```suggestion
        """Sets the last input time to the current time"""
```

2022-06-04 15:33 UTC, MaFeLP commented on pokete_classes/timer.py
> +        ftime = self.time.formated().replace(":", "")
Method has been renamed above.

```suggestion
        ftime = self.time.formatted().replace(":", "")
```

2022-06-04 15:33 UTC, MaFeLP commented on pokete_classes/timer.py
> +"""Contains Classes to manage ingame time"""
```suggestion
"""Contains Classes to manage in-game time"""
```

2022-06-04 15:33 UTC, MaFeLP commented on pokete.py
> +                        "playmap_7." + i not in figure.used_npcs or not save_trainers]:
```suggestion
                + [i.main_ob for i in _map.trainers]\
                + [obmp.ob_maps["playmap_7"].get_obj(i)
                    for i in p_data.map_data["playmap_7"]["balls"] if
                    "playmap_7." + i not in figure.used_npcs
                    or not save_trainers]:
```

2022-06-04 15:33 UTC, MaFeLP commented on pokete.py
> +            _npc["x"], _npc["y"])
```suggestion
                                             _npc["x"], _npc["y"])
```

2022-06-04 15:33 UTC, MaFeLP commented on pokete.py
> -
There should be two empty lines, so no deletion of the line is necessary.

```suggestion

```

2022-06-04 16:29 UTC, lxgr-linux commented on pokete_classes/event.py
> +        self.emit_fn()
But in this case the best way to handle this would be to throw an error, and that's actually what will happen.

2022-06-04 16:42 UTC, lxgr-linux commented
> Nice work!

Thanks alot, I hope this will improve the game.

2022-06-04 20:38 UTC, MaFeLP approved these changes
Nice idea! Keep those coming!

2022-06-04 21:02 UTC, merged