Bugfix
lxgr-linux/pokete pull request #126
Opened 2022-05-11 22:15 UTC by lxgr-linux

Added GameMaps for bug fixes and future compatibility with methods needing the name attribute

2022-06-05 13:50 UTC, lxgr-linux commented
Rebased and ready for review.

2022-06-06 12:44 UTC, MaFeLP requested changes

2022-06-06 12:44 UTC, MaFeLP commented on pokete_classes/animations.py
```suggestion


```

2022-06-06 12:44 UTC, MaFeLP commented on pokete_classes/game_map.py
> +
```suggestion


```

2022-06-06 12:44 UTC, MaFeLP commented on pokete_classes/game_map.py
> +        name: The maps name"""
```suggestion
        height: The map's height
        width: The map's width
        background: The map's background
        name: The map's name"""
```

2022-06-06 13:49 UTC, MaFeLP requested changes

2022-06-06 13:49 UTC, MaFeLP commented on pokete_classes/animations.py
>  def transition(_map, poke):
```suggestion
import pokete_classes.game_map as gm


def transition(_map, poke):
```

2022-06-06 21:07 UTC, merged