change save directory to ~/.local/share/pokete, and add migrate.sh to copy the data over
lxgr-linux/pokete pull request #161
Opened 2022-06-15 14:45 UTC by greatericontop

It's not a great idea to set it to `~/.cache`, because this directory is supposed to be temporary and could be cleared every so often. People also sometimes clear it as it tends to get quite large over time.

2022-06-15 15:17 UTC, lxgr-linux requested changes
Since it was requested here #137, I think it's a good idea to use the `$XDG_DATA_HOME` environment variable to determine the save location.

2022-06-15 15:17 UTC, lxgr-linux commented on release.py
```suggestion
import os
from pathlib import Path


```

2022-06-15 15:17 UTC, lxgr-linux commented on release.py
> +SAVEPATH = "/.local/share/pokete"
```suggestion
SAVEPATH = os.environ.get("XDG_DATA_HOME", str(Path.home)+"/.local/share") + "/pokete"
```

2022-06-15 15:18 UTC, lxgr-linux commented
@daynetran

2022-06-15 17:12 UTC, lxgr-linux commented on release.py
Your forgot to apply this

2022-06-15 19:37 UTC, MaFeLP commented
Thank you for your contribution.

I would just like to have it fully backwards compatible, which means for me no user intervention required.
I would therefore love to see a check, if data in the `SAVEPATH` exists, and if not, try to load it from the old save location. If there also is no data to be found, start a 'fresh' instance of pokete.

2022-06-19 21:05 UTC, lxgr-linux commented
Ready for review @MaFeLP

2022-06-20 20:52 UTC, merged