Here comes a way better implementation of playsound
lxgr-linux/pokete pull request #222
Opened 2022-07-25 20:05 UTC by lxgr-linux

still needs to be tested on OSX

2022-07-25 21:19 UTC, lxgr-linux commented
To build on OSX try:
`go build -ldflags "-s -w" -buildmode=c-shared -o ./libplaysound.osx.so`
@MaFeLP

2022-07-27 11:48 UTC, MaFeLP commented
## Review checklist
- [x] Works on macOS
- [ ] Works on Linux
- [ ] Works on Windows

## Suggestions
- GitHub action that automatically builds the library on/and pushes to master, if the path `playsound` has been modified.

2022-07-27 11:51 UTC, lxgr-linux commented
It would be nice if you could push the compile osx binary.

2022-07-27 12:09 UTC, lxgr-linux commented
> GitHub action that automatically builds the library on/and pushes to master, if the path playsound has been modified.

Thats a good idea, I also found an action that makes the go setup for osx very easy: https://github.com/marketplace/actions/action-gobrew

Did you have to install any compilers like gcc or xcode on macOS?

2022-07-27 12:11 UTC, MaFeLP commented
Does not work on my Linux machine, but also does not crash. Here is `pokete.log`:

```log
[2022-07-27 14:08:32,309][INFO]: === Startup Pokete Grey Edition v0.8.0 ===
[2022-07-27 14:08:32,310][INFO]: [General] 0 mods are loaded: ()
[2022-07-27 14:08:32,846][INFO]: [General] Startup took 0.556561s
[2022-07-27 14:08:32,858][INFO]: [Playsound] playing /mnt/Data/pokete/assets/music/03 Chibi Ninja.mp3
[2022-07-27 14:08:39,243][INFO]: [Fight] Started between Steini (<class '__main__.Figure'>) lvl. 7and Horny (<class 'pokete_classes.providers.NatureProvider'>) lvl. 4
[2022-07-27 14:08:39,246][INFO]: [Playsound] playing /mnt/Data/pokete/assets/music/xDeviruchi - Decisive Battle (Loop).mp3
[2022-07-27 14:08:45,903][INFO]: [Poke][Steini] Used Tackle: {'eff': 1, 'n_hp': 3}
[2022-07-27 14:08:47,910][INFO]: [Poke][Horny] Used Meat Skewer: {'eff': 1, 'n_hp': 3}
[2022-07-27 14:08:59,391][INFO]: [Poke][Steini] Used Tackle: {'eff': 1, 'n_hp': 3}
[2022-07-27 14:09:01,096][INFO]: [Poke][Horny] Used Tackle: {'eff': 1, 'n_hp': 0}
[2022-07-27 14:09:04,111][INFO]: [Poke][Steini] Used Tackle: {'eff': 1, 'n_hp': 2}
[2022-07-27 14:09:05,917][INFO]: [Poke][Horny] Used Tackle: {'eff': 1, 'n_hp': 1}
[2022-07-27 14:09:08,981][INFO]: [Poke][Steini] Used Tackle: {'eff': 1, 'n_hp': 3}
[2022-07-27 14:09:10,888][INFO]: [Poke][Horny] Used Tackle: {'eff': 1, 'n_hp': 2}
[2022-07-27 14:09:13,200][INFO]: [Poke][Steini] Used Tackle: {'eff': 1, 'n_hp': 2}
[2022-07-27 14:09:15,106][INFO]: [Poke][Horny] Used Tackle: {'eff': 1, 'n_hp': 2}
[2022-07-27 14:09:19,573][INFO]: [Poke][Steini] Used Tackle: {'eff': 1, 'n_hp': 2}
[2022-07-27 14:09:21,479][INFO]: [Poke][Horny] Used Tackle: {'eff': 1, 'n_hp': 2}
[2022-07-27 14:09:25,145][INFO]: [Poke][Steini] Used Tackle: {'eff': 1, 'n_hp': 2}
[2022-07-27 14:09:27,251][INFO]: [Poke][Horny] Used Meat Skewer: {'eff': 1, 'n_hp': 4}
[2022-07-27 14:09:29,961][INFO]: [Poke][Steini] Used Tackle: {'eff': 1, 'n_hp': 3}
[2022-07-27 14:09:30,469][INFO]: [Playsound] playing /mnt/Data/pokete/assets/music/xDeviruchi - Decisive Battle (End).mp3
[2022-07-27 14:09:31,466][INFO]: [Poke][Steini] Gained 2xp (curr:52)
[2022-07-27 14:09:32,671][INFO]: [Fight] Ended, Steini(player) won
[2022-07-27 14:09:32,677][INFO]: [Playsound] playing /mnt/Data/pokete/assets/music/03 Chibi Ninja.mp3
[2022-07-27 14:09:34,271][INFO]: [Fight] Started between Steini (<class '__main__.Figure'>) lvl. 7and Vogli (<class 'pokete_classes.providers.NatureProvider'>) lvl. 4
[2022-07-27 14:09:34,276][INFO]: [Playsound] playing /mnt/Data/pokete/assets/music/xDeviruchi - Decisive Battle (Loop).mp3
[2022-07-27 14:09:42,027][INFO]: [Poke][Vogli] Used Power Peck: {'eff': 0.5, 'n_hp': 1}
[2022-07-27 14:09:46,743][INFO]: [Poke][Vogli] Used Tackle: {'eff': 1, 'n_hp': 2}
[2022-07-27 14:09:47,606][INFO]: [Playsound] playing /mnt/Data/pokete/assets/music/xDeviruchi - Decisive Battle (End).mp3
[2022-07-27 14:09:49,606][INFO]: [Fight] Ended, ran away
[2022-07-27 14:09:49,613][INFO]: [Playsound] playing /mnt/Data/pokete/assets/music/03 Chibi Ninja.mp3
[2022-07-27 14:09:54,277][INFO]: [Playsound] playing /mnt/Data/pokete/assets/music/Map.mp3
[2022-07-27 14:09:57,890][INFO]: [Playsound] playing /mnt/Data/pokete/assets/music/03 Chibi Ninja.mp3
[2022-07-27 14:09:59,710][INFO]: [General] Saved
[2022-07-27 14:09:59,710][INFO]: [General] Exiting...
```

2022-07-27 12:13 UTC, MaFeLP commented
> > GitHub action that automatically builds the library on/and pushes to master, if the path playsound has been modified.
> 
> Thats a good idea, I also found an action that makes the go setup for osx very easy: https://github.com/marketplace/actions/action-gobrew
> 
> Did you have to install any compilers like gcc or xcode on macOS?

Go, xcode and gcc are all installed by default: https://github.com/actions/virtual-environments/blob/main/images/macos/macos-12-Readme.md

2022-07-27 12:13 UTC, lxgr-linux commented
And you don't get any panic calls?

2022-07-27 12:13 UTC, MaFeLP commented
> And you don't get any panic calls?

No.

2022-07-27 12:15 UTC, lxgr-linux commented
Are you running it in a virtual env?

2022-07-27 13:58 UTC, MaFeLP commented
Ok. Turns out it was my wrongly configured audio system.....

2022-07-27 15:11 UTC, MaFeLP requested changes
- `assets/AppImageBuilder.yml`:
  - [ ] Remove line 43
  - [ ] Remove unneeded go libraries (`libplaysound.osx.so` and `libplaysound.dll`) from playsound folder to make size smaller.

2022-07-27 15:11 UTC, MaFeLP commented on playsound/__init__.py
> +import time
Unneeded import

```suggestion
```

2022-07-27 15:11 UTC, MaFeLP commented on playsound/__init__.py
> +    """plays an mp3 file
```suggestion
    """Plays a mp3 file
```

2022-07-27 15:11 UTC, MaFeLP commented on playsound/README.md
> +```
```suggestion
```shell
```

2022-07-27 15:11 UTC, MaFeLP commented on playsound/README.md
> +```
```suggestion
```shell
```

2022-07-27 15:11 UTC, MaFeLP commented on playsound/README.md
> +```
```suggestion
```shell
```

2022-07-27 15:11 UTC, MaFeLP commented on README.md
>  For Windows:
Some windows antivirus flag the .dll as malicious:

```suggestion
For Windows:

Some windows antivirus may flag the `libplaysound.dll` as malicious. If pokete crashes, please make sure that the .dll exists and is **not** in quarantine!

```

2022-07-27 17:17 UTC, MaFeLP approved these changes
LGTM

2022-07-27 17:18 UTC, merged