Feature/volume settings
lxgr-linux/pokete pull request #238
Opened 2022-08-21 18:58 UTC by ondrejmyska

Draft of proposal with audio volume settings. There is a few conceptual changes I would like to discuss when the feature is interesting for you.

1. volume level is stored in root level of pokete.json file. Originally, I wanted to store it to the settings, but there are only boolean values, not e.g. inteeger values.
2. Menu - audio setting are flat - placed on the same level. Nice to have feature would be have posibility to group related settings: 
  Audio settings
   - Audio: on
   - Audio volume: 100
![obrazek](https://user-images.githubusercontent.com/5269369/185806451-d52241e6-cbb6-4dd5-8e8f-f63f60bab922.png)
3. Maybe better validation of interval inteeger values. Current implementation is best efford, maybe sufficicent.

Changes are without binary files. I cannot compile all supported architecture. Cross compiling is not working for me. I've tested it with windows rebuilded library.

What do you think about it?

2022-08-21 19:59 UTC, lxgr-linux commented
Ohh, that's very nice.
Actually that's a feature @MaFeLP and I have been talking about since sound was added to the game.

> volume level is stored in root level of pokete.json file. Originally, I wanted to store it to the settings, but there are only boolean values, not e.g. inteeger values.

The settings support all kind of data types, even the `VisSetting`s support setting all values, not just integers. But until now, at least on the master branch, there was no need for non boolean settings, but those are supported by the settingsystem.

> Menu - audio setting are flat - placed on the same level. Nice to have feature would be have posibility to group related settings:
Audio settings

That's very intuitive.

> Maybe better validation of interval inteeger values. Current implementation is best efford, maybe sufficicent.

I also thought about some kind of a nice looking volume slider, able to be manipulated with `a` and `d`.

2022-08-21 20:02 UTC, lxgr-linux commented
I will now myself look into integrating with the settings system.

2022-08-21 20:31 UTC, lxgr-linux commented
I now involved the settingsystem and made the audio settings reactive, so they apply immediately after change.

2022-08-21 20:47 UTC, lxgr-linux commented
> I also thought about some kind of a nice looking volume slider, able to be manipulated with a and d.

I would suggest having a slider like this.

![image](https://user-images.githubusercontent.com/64218491/185810230-491738be-3ccc-401e-b390-26743caf1a88.png)

2022-08-22 10:33 UTC, ondrejmyska commented
> I now involved the settingsystem and made the audio settings reactive, so they apply immediately after change.

Perfect, I forgot to do that

2022-08-22 10:33 UTC, ondrejmyska commented
> I now involved the settingsystem and made the audio settings reactive, so they apply immediately after change.

Thanks!

2022-08-22 10:37 UTC, ondrejmyska commented
> 



> > I also thought about some kind of a nice looking volume slider, able to be manipulated with a and d.
> 
> I would suggest having a slider like this.
> 
> ![image](https://user-images.githubusercontent.com/64218491/185810230-491738be-3ccc-401e-b390-26743caf1a88.png)

Nice suggestion, I like this idea. Especially, colorful levels are intiutive from UX point of view. Will you add slider in separate PR?

2022-08-22 10:43 UTC, lxgr-linux commented
> > 
> 
> > > I also thought about some kind of a nice looking volume slider, able to be manipulated with a and d.
> > 
> > 
> > I would suggest having a slider like this.
> > ![image](https://user-images.githubusercontent.com/64218491/185810230-491738be-3ccc-401e-b390-26743caf1a88.png)
> 
> Nice suggestion, I like this idea. Especially, colorful levels are intiutive from UX point of view. Will you add slider in separate PR?

Yes, I can do that, is this now open for review?

2022-08-22 10:56 UTC, ondrejmyska commented
> 



> > > 
> > 
> > 
> > > > I also thought about some kind of a nice looking volume slider, able to be manipulated with a and d.
> > > 
> > > 
> > > I would suggest having a slider like this.
> > > ![image](https://user-images.githubusercontent.com/64218491/185810230-491738be-3ccc-401e-b390-26743caf1a88.png)
> > 
> > 
> > Nice suggestion, I like this idea. Especially, colorful levels are intiutive from UX point of view. Will you add slider in separate PR?
> 
> Yes, I can do that, is this now open for review?

Almost, I think recompiled macOS playsound library libplaysound.osx.so is still missing.

2022-08-22 11:05 UTC, lxgr-linux commented
> > 
> 
> > > > 
> > > 
> > > 
> > > > > I also thought about some kind of a nice looking volume slider, able to be manipulated with a and d.
> > > > 
> > > > 
> > > > I would suggest having a slider like this.
> > > > ![image](https://user-images.githubusercontent.com/64218491/185810230-491738be-3ccc-401e-b390-26743caf1a88.png)
> > > 
> > > 
> > > Nice suggestion, I like this idea. Especially, colorful levels are intiutive from UX point of view. Will you add slider in separate PR?
> > 
> > 
> > Yes, I can do that, is this now open for review?
> 
> Almost, I think recompiled macOS playsound library libplaysound.osx.so is still missing.

Since I don't own a mac either and can't crosscompile for OSX I think we have to rely on @MaFeLP

2022-08-22 14:58 UTC, lxgr-linux requested changes
Just some doc strings.

2022-08-22 14:58 UTC, lxgr-linux commented on playsound/__init__.py
>          file: path to file"""
```suggestion
        file: path to file
        volume: the sound volume as an int 0-100"""
```

2022-08-22 14:58 UTC, lxgr-linux commented on pokete_classes/audio.py
>      """plays a song in loop"""
```suggestion
    """plays a song in loop
    ARGS:
        song: path to file
        play_audio: bool whether or not audio actually should be played
        volume: the sound volume as an int 0-100"""
```

2022-08-22 18:41 UTC, ondrejmyska commented
> Just some doc strings.

Thank's, I've just applied you suggestions directly from Github web interface. Interesting tool :)

2022-08-22 18:45 UTC, lxgr-linux commented
> > Just some doc strings.
> 
> Thank's, I've just applied you suggestions directly from Github web interface. Interesting tool :)

Oh yes, it's quite nice, and also automatically makes the person suggesting the changes Co-author.

2022-08-22 18:48 UTC, lxgr-linux approved these changes
LGTM

2022-08-27 19:00 UTC, MaFeLP requested changes
LGTM

2022-08-27 19:01 UTC, MaFeLP approved these changes
*LGTM

2022-08-28 08:30 UTC, merged